name: health_planner_models
description: A library for my project.
version: 0.1.0
author: Edwin Liu
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  json_serializable: ^4.1.3
  json_annotation: ^4.0.1
  flutter_quill: ^1.6.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5

flutter:
