name: health_planner_models
description: A library for my project.
version: 0.0.1
author: Edwin Liu
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
